// Type definition for each icon's name and path
interface SvgIcon {
    name: string;
    path: string;
}

// List of neutral SVG icons
export const neutralSvgIcons: SvgIcon[] = [
    { name: 'Bootstrap', path: '/src/assets/icons/neutral/Bootstrap.svg' },
    { name: 'C', path: '/src/assets/icons/neutral/C.svg' },
    { name: 'C++', path: '/src/assets/icons/neutral/CPP.svg' },
    { name: 'C#', path: '/src/assets/icons/neutral/CS.svg' },
    { name: 'CSS', path: '/src/assets/icons/neutral/CSS.svg' },
    { name: 'Discord', path: '/src/assets/icons/neutral/Discord.svg' },
    { name: 'Django', path: '/src/assets/icons/neutral/Django.svg' },
    { name: '.NET', path: '/src/assets/icons/neutral/DotNet.svg' },
    { name: 'Git', path: '/src/assets/icons/neutral/Git.svg' },
    { name: 'Heroku', path: '/src/assets/icons/neutral/Heroku.svg' },
    { name: 'HTML', path: '/src/assets/icons/neutral/HTML.svg' },
    { name: 'JavaScript', path: '/src/assets/icons/neutral/JavaScript.svg' },
    { name: 'Nginx', path: '/src/assets/icons/neutral/Nginx.svg' },
    { name: 'Postman', path: '/src/assets/icons/neutral/Postman.svg' },
    { name: 'Redux', path: '/src/assets/icons/neutral/Redux.svg' },
    { name: 'Sass', path: '/src/assets/icons/neutral/Sass.svg' },
    { name: 'SQLite', path: '/src/assets/icons/neutral/SQLite.svg' },
    { name: 'Styled Components', path: '/src/assets/icons/neutral/StyledComponents.svg' },
    { name: 'TypeScript', path: '/src/assets/icons/neutral/TypeScript.svg' },
];

// List of dark SVG icons
export const darkSvgIcons: SvgIcon[] = [
    { name: 'Azure', path: '/src/assets/icons/dark/Azure-Dark.svg' },
    { name: 'Bash', path: '/src/assets/icons/dark/Bash-Dark.svg' },
    { name: 'CodePen', path: '/src/assets/icons/dark/CodePen-Dark.svg' },
    { name: 'Dart', path: '/src/assets/icons/dark/Dart-Dark.svg' },
    { name: 'DiscordJS', path: '/src/assets/icons/dark/DiscordJS-Dark.svg' },
    { name: 'Eclipse', path: '/src/assets/icons/dark/Eclipse-Dark.svg' },
    { name: 'ExpressJS', path: '/src/assets/icons/dark/ExpressJS-Dark.svg' },
    { name: 'Figma', path: '/src/assets/icons/dark/Figma-Dark.svg' },
    { name: 'Firebase', path: '/src/assets/icons/dark/Firebase-Dark.svg' },
    { name: 'Flask', path: '/src/assets/icons/dark/Flask-Dark.svg' },
    { name: 'Flutter', path: '/src/assets/icons/dark/Flutter-Dark.svg' },
    { name: 'GitHub', path: '/src/assets/icons/dark/Github-Dark.svg' },
    { name: 'Gmail', path: '/src/assets/icons/dark/Gmail-Dark.svg' },
    { name: 'Java', path: '/src/assets/icons/dark/Java-Dark.svg' },
    { name: 'Kali Linux', path: '/src/assets/icons/dark/Kali-Dark.svg' },
    { name: 'Laravel', path: '/src/assets/icons/dark/Laravel-Dark.svg' },
    { name: 'Linux', path: '/src/assets/icons/dark/Linux-Dark.svg' },
    { name: 'Material UI', path: '/src/assets/icons/dark/MaterialUI-Dark.svg' },
    { name: 'MySQL', path: '/src/assets/icons/dark/MySQL-Dark.svg' },
    { name: 'Netlify', path: '/src/assets/icons/dark/Netlify-Dark.svg' },
    { name: 'Next.js', path: '/src/assets/icons/dark/NextJS-Dark.svg' },
    { name: 'Node.js', path: '/src/assets/icons/dark/NodeJS-Dark.svg' },
    { name: 'Notion', path: '/src/assets/icons/dark/Notion-Dark.svg' },
    { name: 'npm', path: '/src/assets/icons/dark/Npm-Dark.svg' },
    { name: 'PHP', path: '/src/assets/icons/dark/PHP-Dark.svg' },
    { name: 'Python', path: '/src/assets/icons/dark/Python-Dark.svg' },
    { name: 'React', path: '/src/assets/icons/dark/React-Dark.svg' },
    { name: 'Tailwind CSS', path: '/src/assets/icons/dark/TailwindCSS-Dark.svg' },
    { name: 'Ubuntu', path: '/src/assets/icons/dark/Ubuntu-Dark.svg' },
    { name: 'Vercel', path: '/src/assets/icons/dark/Vercel-Dark.svg' },
    { name: 'Visual Studio', path: '/src/assets/icons/dark/VisualStudio-Dark.svg' },
    { name: 'Vite', path: '/src/assets/icons/dark/Vite-Dark.svg' },
    { name: 'VS Code', path: '/src/assets/icons/dark/VSCode-Dark.svg' },
    { name: 'Windows', path: '/src/assets/icons/dark/Windows-Dark.svg' },
    { name: 'Yarn', path: '/src/assets/icons/dark/Yarn-Dark.svg' },
];

// List of light SVG icons
export const lightSvgIcons: SvgIcon[] = [
    { name: 'Azure', path: '/src/assets/icons/light/Azure-Light.svg' },
    { name: 'Bash', path: '/src/assets/icons/light/Bash-Light.svg' },
    { name: 'CodePen', path: '/src/assets/icons/light/CodePen-Light.svg' },
    { name: 'Dart', path: '/src/assets/icons/light/Dart-Light.svg' },
    { name: 'DiscordJS', path: '/src/assets/icons/light/DiscordJS-Light.svg' },
    { name: 'Eclipse', path: '/src/assets/icons/light/Eclipse-Light.svg' },
    { name: 'ExpressJS', path: '/src/assets/icons/light/ExpressJS-Light.svg' },
    { name: 'Figma', path: '/src/assets/icons/light/Figma-Light.svg' },
    { name: 'Firebase', path: '/src/assets/icons/light/Firebase-Light.svg' },
    { name: 'Flask', path: '/src/assets/icons/light/Flask-Light.svg' },
    { name: 'Flutter', path: '/src/assets/icons/light/Flutter-Light.svg' },
    { name: 'GitHub', path: '/src/assets/icons/light/Github-Light.svg' },
    { name: 'Gmail', path: '/src/assets/icons/light/Gmail-Light.svg' },
    { name: 'Java', path: '/src/assets/icons/light/Java-Light.svg' },
    { name: 'Kali Linux', path: '/src/assets/icons/light/Kali-Light.svg' },
    { name: 'Laravel', path: '/src/assets/icons/light/Laravel-Light.svg' },
    { name: 'Linux', path: '/src/assets/icons/light/Linux-Light.svg' },
    { name: 'Material UI', path: '/src/assets/icons/light/MaterialUI-Light.svg' },
    { name: 'MySQL', path: '/src/assets/icons/light/MySQL-Light.svg' },
    { name: 'Netlify', path: '/src/assets/icons/light/Netlify-Light.svg' },
    { name: 'Next.js', path: '/src/assets/icons/light/NextJS-Light.svg' },
    { name: 'Node.js', path: '/src/assets/icons/light/NodeJS-Light.svg' },
    { name: 'Notion', path: '/src/assets/icons/light/Notion-Light.svg' },
    { name: 'npm', path: '/src/assets/icons/light/Npm-Light.svg' },
    { name: 'PHP', path: '/src/assets/icons/light/PHP-Light.svg' },
    { name: 'Python', path: '/src/assets/icons/light/Python-Light.svg' },
    { name: 'React', path: '/src/assets/icons/light/React-Light.svg' },
    { name: 'Tailwind CSS', path: '/src/assets/icons/light/TailwindCSS-Light.svg' },
    { name: 'Ubuntu', path: '/src/assets/icons/light/Ubuntu-Light.svg' },
    { name: 'Vercel', path: '/src/assets/icons/light/Vercel-Light.svg' },
    { name: 'Visual Studio', path: '/src/assets/icons/light/VisualStudio-Light.svg' },
    { name: 'Vite', path: '/src/assets/icons/light/Vite-Light.svg' },
    { name: 'VS Code', path: '/src/assets/icons/light/VSCode-Light.svg' },
    { name: 'Windows', path: '/src/assets/icons/light/Windows-Light.svg' },
    { name: 'Yarn', path: '/src/assets/icons/light/Yarn-Light.svg' },
];